name: C/C++ CI

on:
  push:
    branches:
      - "main"
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: textbook/git-checkout-submodule-action@master
    - name: Compilation
      run: make --jobs=4 --output-sync=target
