name: Pandoc/Latex CI

on:
  push:
    branches:
      - "main"
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc and pdflatex
      run: sudo apt-get install -y pandoc texlive-base latex texlive-latex-recommended texlive-latex-extra texlive-lang-portuguese
    - name: Latex Compilation
      run: make relatorio.pdf
