name: Pandoc/Latex CI

on:
  push:
    branches:
      - "main"
      - "**"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install pandoc and pdflatex
      run: sudo apt-get install -y pandoc texlive-full
    - name: Markdown Compilation
      run: make relatorio.pdf
    - name: Latex Compilation
      run: make Relatorio-RC-Meta_2/main.pdf
